### ISSUE TITLE
US - Cadastro de supermercados na plataforma (frontend)

### ISSUE THREAD

**Issue by WelisonR** [Projeto-Integrador-2-2020-2-Grupo-08/documentacao#10]
## Descrição

Eu, como Supermercado, gostaria de **realizar cadastro na aplicação** para **fazer uso de todas as funcionalidades do sistema**.

## Tarefas

- [x] Adicionar todos os campos de informação presentes no protótipo (abaixo);
- [x] Validar preenchimento dos campos;
- [x] Enviar ao back-end a solicitação de cadastro;
- [x] Apresentar tela de sucesso.

## Critérios de Aceitação [?](http://www.metodoagil.com/historias-de-usuario/)

- Páginas funcionais para criação de supermercados no sistema.

## Screenshots

![Cadastro - Supermercados](https://user-images.githubusercontent.com/31112450/114637954-e83dd980-9ca0-11eb-848a-8dbd5136aba6.png)

![Sucesso - Cadastro supermercados](https://user-images.githubusercontent.com/31112450/114638049-21764980-9ca1-11eb-95b4-43b1c80469e9.png)

**Comment by andrelucax** [comment]
Resolvido no [FRONT PR-3](https://github.com/Projeto-ECOmposteira/frontend/pull/3)
