### ISSUE TITLE
US - Simulação de envio de dados das composteiras

### ISSUE THREAD

**Issue by WelisonR** [Projeto-Integrador-2-2020-2-Grupo-08/documentacao#4]
## Descrição

Eu, como Desenvolvedor, gostaria de **simular os dados enviados pelos sensores da composteira** para **validar o funcionamento dos sistemas que deles dependem**.

## Tarefas

- [x] Criar _script_, seja em python ou C, que realiza o envio de todos os dados da composteira por MQTT (se tiver disponível, programar em uma esp32).

## Critérios de Aceitação [?](http://www.metodoagil.com/historias-de-usuario/)

- Software simula o funcionamento de uma composteira de modo a enviar os dados através de protocolo MQTT os dados da composteira;
- Enviar os dados como json válido.

**Comment by Bumbleblo** [comment]
O script ta na branch dev no momento vou melhorar a documentação para revisão.
