### ISSUE TITLE
US - Configurações iniciais da estrutura da API Gateway

### ISSUE THREAD

**Issue by WelisonR** [Projeto-Integrador-2-2020-2-Grupo-08/documentacao#6]
## Descrição

Eu, como desenvolvedor, gostaria de **configurar uma API gateway** para **acesso unificado aos serviços do sistema**.

## Tarefas

- [x] Iniciar uma aplicação django;
- [x] Realizar configurações iniciais da API Gateway;
- [x] Configurar inicialmente a rota que realiza e persiste o login na aplicação.

## Critérios de Aceitação [?](http://www.metodoagil.com/historias-de-usuario/)

- API Gateway configurada.

**Comment by andrelucax** [comment]
Issue fechada no repositorio da API gateway, ambiente dockerzado django criado com os seguintes endpoints:

register:
   IP:PORTA/api/register/
   campos necessarios: username (vai ser o email), password, password2, first_name, last_name

login:
   IP:PORTA/api/login/
   campos necessarios: username, password

check_token:
   IP:PORTA/api/check_token/
   campos necessarios: acces-token, refresh-token (são retornos da funcao de login)
